In [1]:
import numpy as np

In [2]:
a=np.array([1,5,10])
print(a)

[ 1  5 10]


In [3]:
b=np.array([[1,7,20],[5,8,9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [4]:
#Dimension ndim=numpy dimension
b.ndim

2

In [5]:
a.ndim

1

In [6]:
#Row and column size
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [9]:
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [8]:
b[0,2]

20

In [10]:
b[0,1:]

array([ 7, 20])

In [11]:
b[1,1]=18
print(b)

[[ 1  7 20]
 [ 5 18  9]]


In [12]:
# create array automatically
array_z=np.zeros((2,3))
array_z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
array_f=np.full((4,4),25)
array_f

array([[25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25]])

In [14]:
array_r=np.random.rand(4,3)
array_r

array([[0.83801253, 0.8405716 , 0.17596351],
       [0.69609972, 0.89143013, 0.68202293],
       [0.97689587, 0.02230573, 0.69149832],
       [0.26490816, 0.44694994, 0.73921866]])

In [15]:
array_ri=np.random.randint(0,100,size=(5,5))
array_ri

array([[94, 82, 27, 12, 69],
       [48, 91, 39, 86, 72],
       [ 3, 79, 50, 12, 51],
       [45,  6, 86, 47, 98],
       [55, 12, 12,  2, 34]])

In [16]:
# Copy!!!!!
a=np.array([1,2,3])
b=a
b[0]=90
print(a)

[90  2  3]


In [17]:
a=np.array([1,2,3])
b=a.copy()
b[0]=90
print(a)

[1 2 3]


In [18]:
# Mathematical Operations
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [19]:
a+4

array([5, 6, 7, 8])

In [20]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [22]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.min(c)

1

In [24]:
np.max(c)

6

In [25]:
np.sum(c)

21

In [28]:
filedate=np.genfromtxt('Example.txt',delimiter=',')
filedata=filedate.astype('int32')
print(filedata)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [11 12 13 14 15 16 17]]
